FROM tomcat:8 
LABEL "author"="DevOps" "Project"="gameoflife"
LABEL "mailid"="abc@gmail.com"
RUN wget https://war-jar-vn.s3.amazonaws.com/gameoflife.war
RUN cp gameoflife.war /usr/local/tomcat/webapps 
EXPOSE 8080
CMD ["catalina.sh", "run"]