FROM maven:3-openjdk-8 as build
RUN apt-get update && apt-get install git -y && git clone https://github.com/wakaleo/game-of-life.git && cd game-of-life && mvn package
FROM tomcat:8 
COPY --from=build game-of-life/gameoflife-web/target/gameoflife.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD ["catalina.sh","run"] 